#!/bin/bash
# Argument $1 is the folder name in your E: partition containing the date-labeled folders of videos
# Argument $2 is the date the data was recorded in YYMMDD format
# Argument $3 is the openmind7 username (same as Kerberos username) for the files to be copied to

# 1. Select fields locally
matlab.exe -r "addpath(genpath('C:/Users/Gurrein Madan/Documents/MATLAB/Patch')), preSplit('$2'), quit"
PROCEED="n"
while [ $PROCEED != "y" ]
do
	echo "Finished selecting fields? (y/n)"
	read PROCEED
done

# 2. Copy over folders containing video files and new fields.mat files
scp -r /mnt/e/'$1'/$2 $3@openmind7.mit.edu:/om/user/$3/data/patch_videos
