#!/bin/bash
# Argument $1 is the date the data was recorded in YYYYMMDD format
# Argument $2 is the openmind7 username (same as Kerberos username) for the files to be copied to

# 1. Select fields locally
matlab.exe -r "addpath(genpath('C:/Users/kamal/Documents/MATLAB/Patch')), preSplit('$1'), quit"
PROCEED="n"
while [ $PROCEED != "y" ]
do
	echo "Finished selecting fields? (y/n)"
	read PROCEED
done

# 2. Mount hard drive (assuming it was unplugged to download vids from behavior computers)
sudo mount -t drvfs G: /mnt/g

# 3. Copy over folders containing video files and new fields.mat files
scp -r /mnt/g/behavior/$1 $2@openmind7.mit.edu:/om/user/$2/data/patch_videos
