#!/bin/bash
# Argument $1 is the date the data was recorded in YYYYMMDD format
# Argument $2 is the openmind7 username (same as Kerberos username) for the files to be copied to

# 1. Select fields locally
PROCEED="n"
echo "Select fields? (y/n)"
read PROCEED
if [ $PROCEED == "y" ]; then
	matlab.exe -r "addpath(genpath('C:/Users/kamal/Documents/MATLAB/Patch')), preSplit('$1'), quit"

	PROCEED="n"
	while [ $PROCEED != "y" ]
	do
		echo "Finished selecting fields? (y/n)"
		read PROCEED
	done
fi

# 2. Mount hard drive (assuming it was unplugged to download vids from behavior computers)
PROCEED="n"
echo "Remount? (y/n)"
read PROCEED
if [ $PROCEED == "y" ]; then
	sudo umount /mnt/g
	sudo rmdir /mnt/g
	sudo mkdir /mnt/g
	sudo mount -t drvfs G: /mnt/g
fi

# 3. Copy over folders containing video files and new fields.mat files
echo "Copying $1 to $2"
scp -r /mnt/g/behavior/$1 $2@openmind7.mit.edu:/om/user/$2/data/patch_videos
