#!/bin/bash
#SBATCH --job-name=processPatchVids
#SBATCH --output=/om/user/kmaher/log/processPatchVids_%j.txt
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=30000
#SBATCH --time=150:00:00

# Argument $1 should be the name (YYYYMMDD) of the folder containing the split videos.

module load mit/matlab/2018a
matlab -nodisplay -singleCompThread -r "addpath(genpath('/om/user/kmaher/scripts/matlab')), processPatchVids('$1')"

# Consider removing /tmp/YYYYMMDD_refeeding* files within the script.
# Will have to be careful in order to avoid erasing others' tmp files if simultaneous patch processing is occurring.
