#!/bin/bash

# Distributed splitting
mkdir /om/user/kmaher/data/patch_videos/$1_unsplit
for subfolder in /om/user/kmaher/data/patch_videos/$1/*; do
	sbatch /om/user/kmaher/scripts/matlab/patch/subsplit $1 $(basename $subfolder)
done
sleep 5h

# Move unsplit videos to unsplit folder
for subfolder in /om/user/kmaher/data/patch_videos/$1/*; do
	if [[ $(basename $subfolder) == *_refeeding_2_* ]]; then
		mv $subfolder /om/user/kmaher/data/patch_videos/$1_unsplit
	fi
done
